name: Giftwrap

on:
  push:
    # branches:
    #   - master
    tags:
      - "*"
      - "!**-beta**"
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Pull global luacheckrc
        run:
          wget -O .luacheckrc https://raw.githubusercontent.com/clicketz/wow-luacheckrc/mainline/.luacheckrc

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1

      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Package
        uses: BigWigsMods/packager@v2
